name: e2e

on: [push]

jobs:
  e2e:
    runs-on: ubuntu-16.04

    steps:
      - uses: actions/checkout@v2
      - run: mkdir -p cypress/screenshots
      - run: mkdir -p cypress/videos
      - name: Cypress run
        uses: cypress-io/github-action@v1
        with:
          start: npm start
          wait-on: 'http://localhost:8000'
          wait-on-timeout: 180
      - uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
      - uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: cypress-videos
          path: cypress/videos
        env:
          CI: true
